workspace/config/routes.rb
Rails.application.routes.draw do

  
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  get 'welcome/misc', to: 'welcome#misc'
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'misc', to: 'pages#misc'

end

workspace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

workspace/app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home

    end
    
    def about
        
    end
    
    def misc

    end
    
end

workspace/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home

    end
    
    def about
        
    end
    
    def misc
        
    end
    
end

workspace/app/helpers/application_helper.rb
module ApplicationHelper
end

workspace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

workspace/app/views/pages/about.html.erb
<h1> This is Stephanie Dungee About Page </h1>

<%= link_to 'Home', root_path %><P>
<%= link_to 'Misc', misc_path %>

workspace/app/views/pages/home.html.erb
<h1> This is Stephanie Dungee first Home Page </h1>

<p><%= image_tag 'thC64LBPBM.jpg' %></p>

<%= link_to 'About', about_path %><P>
<%= link_to 'Misc', misc_path %>

workspace/app/views/pages/misc.html.erb
<h1> This is Stephanie Dungee Misc Page </h1>

<%= link_to 'Home', root_path %><P>
<%= link_to 'About', about_path %>

workspace/app/views/welcome/about.html.erb
<h1> Hello this my About Page</h1>


<%= link_to 'Home', welcome_home_path %><P>
<%= link_to 'Misc', welcome_misc_path %>

workspace/app/views/welcome/home.html.erb
<h1> This is my Home Page</h1>

<p><%= image_tag 'thC64LBPBM.jpg' %></p>

<%= link_to 'About', welcome_about_path %><P>
<%= link_to 'Misc', welcome_misc_path %>

workspace/app/views/welcome/misc.html.erb
<h1> This is my Misc Page </h1>

<%= link_to 'Home', welcome_home_path %><P>
<%= link_to 'About', welcome_about_path %>